package org.virginiaso.score_scope_export;

public enum ConfigItem {
	APPLICATION_ID,
	DUOSMIUM_SCENE,
	TOURNAMENT_TRACKS_VIEW(DUOSMIUM_SCENE),
	TEAM_RESULTS_VIEW(DUOSMIUM_SCENE),
	RANKS_VIEW(DUOSMIUM_SCENE),

	// The rest are field IDs:
	EVENTS_BY_TRACK_EVENT_NAME,
	RAW_SCORES_DUOSMIUM_RANK,
	RAW_SCORES_IS_TRIAL_EVENT,
	SCHOOL_CITY_STATE,
	SCHOOL_AWARD_CEREMONY_NAME,
	TEAMS_IS_EXHIBITION_TEAM,
	TEAMS_PENALTY,
	TEAMS_SUMMED_TEAM_POINT_SCORE,
	TEAMS_TEAM_NAME,
	TEAMS_TEAM_NUM,
	TEAMS_TEAM_POINT_SCORE,
	TEAMS_TOURNAMENT_TRACK,
	TOURNAMENTS_IS_STATE_TOURNAMENT,
	TOURNAMENTS_ONE_TROPHY_PER,
	TOURNAMENTS_TOURNAMENT_DATE,
	TOURNAMENT_TRACK_DIVISION,
	TOURNAMENT_TRACK_FULL_TOURNAMENT_NAME,
	TOURNAMENT_TRACK_NUM_MEDALS,
	TOURNAMENT_TRACK_NUM_SCHOOLS_PROGRESSING,
	TOURNAMENT_TRACK_NUM_TROPHIES;

	private final ConfigItem associatedScene;

	private ConfigItem() {
		this.associatedScene = null;
	}

	private ConfigItem(ConfigItem associatedScene) {
		this.associatedScene = associatedScene;
	}

	public ConfigItem getAssociatedScene() {
		return associatedScene;
	}
}
