package org.virginiaso.score_scope_export;

public enum Field {
	DIVISION_DIVISION,
	EVENTS_BY_TOURNAMENT_DIVISION,
	EVENTS_BY_TOURNAMENT_EVENT_NAME,
	EVENTS_BY_TOURNAMENT_TOURNAMENT,
	RAW_SCORES_DUOSMIUM_RANK,
	RAW_SCORES_IS_TRIAL_EVENT,
	SCHOOL_CITY_STATE,
	SCHOOL_SCHOOL_NAME,
	TEAMS_EXHIBITION_TEAM,
	TEAMS_PENALTY,
	TEAMS_SUMMED_TEAM_POINT_SCORE,
	TEAMS_TEAM_NAME,
	TEAMS_TEAM_NUM,
	TEAMS_TEAM_POINT_SCORE,
	TOURNAMENTS_TOURNAMENT_DATE,
	TOURNAMENTS_TOURNAMENT_NAME,
	TOURNAMENTS_NUM_B_BIDS,
	TOURNAMENTS_NUM_B_MEDALS,
	TOURNAMENTS_NUM_B_TROPHIES,
	TOURNAMENTS_NUM_C_BIDS,
	TOURNAMENTS_NUM_C_MEDALS,
	TOURNAMENTS_NUM_C_TROPHIES,
	TOURNAMENTS_ONE_TROPHY_PER,
	TOURNAMENTS_IS_STATE_TOURNAMENT,
	TOURNAMENTS_TOURNAMENT;
}
